config/routes.rb
Rails.application.routes.draw do
  # get 'consignments/new'
  root 'top_pages#top'
  
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations' # ユーザー情報更新
  }
  
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy' # logout
  end
  
  resources :admins, only: %i(show index)
  
  resources :users, only: %i(index show update destroy) do
    resources :consignments do
      collection do
        get 'by_customer', to: 'consignments#by_customer'
        get 'by_user', to: 'consignments#by_user'
        get 'by_product', to: 'consignments#by_product'
        get 'documents'
      end
      resources :stocks
    end
    member do
      patch 'password_update' # パスワード更新
      get 'end_tasks'
    end
  end
  
  resources :products do
    collection do
      post 'import'
    end
  end
  
  resources :customers do
    collection do
      post 'import'
    end
  end
  
  resources :posts, only: %i(show edit update)
  
  post 'callback', to: 'linebot#callback'

end

app/views/admins/_users_form.html.erb
<%= form_with(model: user, local: true, method: :patch) do |f| %>
  <%= f.number_field :code, placeholder: "#{User.human_attribute_name :code}", class: "form-control" %>
  <%= f.text_field :name, placeholder: "#{User.human_attribute_name :name}", class: "form-control" %>
  <%= f.email_field :email, placeholder: "#{User.human_attribute_name :email}", class: "form-control" %>
  <%= f.submit "更新", data: { confirm: "#{user.name}の情報を更新してよろしいですか？" }, class: "btn btn-default btn-block" %>
<% end %>

app/views/admins/_users_password_form.html.erb
<%= form_with(model: user,url: password_update_user_path(user), local: true, method: :patch) do |f| %>
  <%= f.password_field :password, placeholder: "#{User.human_attribute_name :password}", class: "form-control" %>
  <%= f.password_field :password_confirmation, placeholder: "#{User.human_attribute_name :password_confirmation}", class: "form-control" %>
  <%= f.submit "パスワード更新", data: { confirm: "#{user.name}のパスワードを更新してよろしいですか？" }, class: "btn btn-danger btn-block" %>
<% end %>

app/views/admins/show.html.erb
<% provide(:title, "管理画面") %>

<div class="container">
  <div class="col col-md-6 offset-md-3 admin-menu">
    <p>一般設定</p>
    <table class="table table-condensed table-hover table-responsive">
      <tr>
        <th>担当者</th>
        <td><%= link_to "登録･修正", users_path %></td>
        <td>登録数&nbsp;<%= User.count %>件</td>
      </tr>
      <tr>
        <th>得意先</th>
        <td><%= link_to "登録･修正", customers_path %></td>
        <td>登録数&nbsp;<%= Customer.count %>件</td>
      </tr>
      <tr>
        <th>商品</th>
        <td><%= link_to "登録･修正", products_path %></td>
        <td>登録数&nbsp;<%= Product.count %>件</td>
      </tr>
    </table>
  </div>
  
  <br>
  
  <div class="col col-md-6 offset-md-3 admin-menu">
    <p>管理者設定</p>
    <table class="table table-condensed table-hover table-responsive">
      <tr>
        <th>管理者</th>
        <td><%= link_to "ログイン情報変更", edit_admin_registration_path %></td>
      </tr>
      <tr>
        <th>LINE通知</th>
        <td><%= link_to "設定変更", edit_post_path(1) %></td>
      </tr>
    </table>
  </div>
</div>

app/views/admins/users_index.html.erb
<% provide(:title, "担当者一覧") %>

<h2><i class="fas fa-user-friends"></i>&nbsp;担当者一覧・編集</h2>
<div class="container">
  <div class="col col-md-12 admin-menu">
    <%= paginate @users %>
    <table class="table-responsive table-bordered table-condensed table-hover bg-light" id="table-users">
      <thead>
        <tr>
          <th></th>
          <th class="pc-display"><%= User.human_attribute_name :code %></th>
          <th><%= User.human_attribute_name :name %></th>
          <th class="pc-display"><%= User.human_attribute_name :email %></th>
        </tr>
      </thead>
      
      <% @users.each do |user| %>
        <tr>
          <td>
            <a class="btn btn-default btn-sm" data-toggle="collapse" href="#collapse1-<%= user.id %>"
               role="button" aria-expanded="false" aria-controls="collapse1-<%= user.id %>">
              編集
            </a>
            <a class="btn btn-danger fas fa-unlock-alt" data-toggle="collapse" href="#collapse2-<%= user.id %>"
               role="button" aria-expanded="false" aria-controls="collapse2-<%= user.id %>">
            </a>
          </td>
          <td class="pc-display"><%= format("%03d", user.code) %></td>
          <td><%= user.name %></td>
          <td class="pc-display"><%= user.email %></td>
        </tr>
        <tr>
          <td colspan="4">
            <div class="collapse" id="collapse1-<%= user.id %>">
              <div class="collapse-body">
                <%= render 'users_form', { user: user } %>
              </div>
            </div>
            <div class="collapse" id="collapse2-<%= user.id %>">
              <div class="collapse-body">
                <%= render 'users_password_form', { user: user } %>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>