config/routes.rb
Rails.application.routes.draw do
  # get 'consignments/new'
  root 'top_pages#top'
  
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations' # ユーザー情報更新
  }
  
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy' # logout
  end
  
  resources :admins, only: %i(show index)
  
  resources :users, only: %i(index show update destroy) do
    resources :consignments do
      collection do
        get 'by_customer', to: 'consignments#by_customer'
        get 'by_user', to: 'consignments#by_user'
        get 'by_product', to: 'consignments#by_product'
        get 'documents'
      end
      resources :stocks
    end
    member do
      patch 'password_update' # パスワード更新
      get 'end_tasks'
    end
  end
  
  resources :products do
    collection do
      post 'import'
    end
  end
  
  resources :customers do
    collection do
      post 'import'
    end
  end
  
  resources :posts, only: %i(show edit update)
  
  post 'callback', to: 'linebot#callback'

end

app/models/user.rb
class User < ApplicationRecord
  has_many :consignments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  # devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :validatable,
  #       :timeoutable
         
 devise :database_authenticatable, :registerable,
         :rememberable, :validatable
         
  CODE_VALUES = 0..999
  validates :code, presence: true, inclusion: { in: CODE_VALUES }, uniqueness: true
  validates :name, presence: true, length: { maximum: 50 }
  
  # パスワードの入力なしでユーザー情報更新
  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: %i(update)

  # GET /resource/sign_up
  def new
    unless admin_signed_in?
      redirect_to root_url
    else
      super
    end
  end

  # POST /resource
  def create
    unless admin_signed_in?
      redirect_to root_url
    else
      # super
      build_resource(sign_up_params)

      resource.save
      yield resource if block_given?
      if resource.persisted?
        if resource.active_for_authentication?
          flash[:notice] = "#{@user.name}さんのアカウントを登録しました。"
          # set_flash_message! :notice, :signed_up
          redirect_to users_url
          # sign_up(resource_name, resource)
          # respond_with resource, location: after_sign_up_path_for(resource)
        else
          set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
          expire_data_after_sign_in!
          respond_with resource, location: after_inactive_sign_up_path_for(resource)
        end
      else
        clean_up_passwords resource
        set_minimum_password_length
        respond_with resource
      end
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # ユーザー情報更新
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:code, :name])
  end
  
  # パスワードの入力なしでユーザー情報更新
  # update_without_current_passwordはuser.rbに記述
  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end
  
  # ユーザー更新後のリダイレクト先
  def after_update_path_for(resource)
    user_path(current_user)
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    if admin_signed_in?
      flash[:alert] = "一度管理アカウントからログインしてください。"
      redirect_to root_url
    else
      super
    end
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user
  before_action :authenticate_admin!, only: %i(create update password_update destroy)
  before_action :set_user, only: %i(show end_tasks update password_update destroy)
  before_action :signed_in_correct_user, only: %i(show end_tasks)
  # before_action :signed_in_correct_user_or_admin, only: %i(show end_tasks)
  
  
  def index
    @users = User.all.page(params[:page]).order(code: :asc)
  end
  
  def show
    redirect_to users_url if admin_signed_in?
    @search_params = consignment_search_params
    @search_none = consignment_search_none
    @user_consignments = @search_none ? @user.consignments.where('done = ?', false).search(@search_params).page(params[:page]).per(10).order(ship_date: :desc).order(product_code: :desc).order(created_at: :desc) : 
                               @user.consignments.where('done = ?', false).search(@search_params).order(ship_date: :desc).order(product_code: :desc).order(created_at: :desc)
  end
  
  def end_tasks
    @search_params = consignment_search_params
    @search_none = consignment_search_none
    @user_consignments = @search_none ? @user.consignments.where('done = ?', true).search(@search_params).page(params[:page]).per(10).order(ship_date: :desc).order(product_code: :desc).order(created_at: :desc) : 
                               @user.consignments.where('done = ?', true).search(@search_params).order(ship_date: :desc).order(product_code: :desc).order(created_at: :desc)
  end
  
  def update
    if @user.update_attributes(user_params)
      # ユーザーモデル(User)を更新した場合、委託(モデルconsignment)の、担当者名(user_name)も同時更新する。
      # Consignment.where(['user_id == ?', @user.id]).update_all(user_name: User.find(@user.id).name) if Consignment.where(user_id: @user.id).present?
      if Rails.env.production?
        Consignment.where(['user_id::integer = ?', @user.id]).update_all(user_name: User.find(@user.id).name) if Consignment.where(['user_id::integer = ?', @user.id]).present?
      else Rails.env.development? || Rails.env.test?
        Consignment.where(['user_id == ?', @user.id]).update_all(user_name: User.find(@user.id).name) if Consignment.where(['user_id == ?', @user.id])
      end
      flash[:notice] = "【#{format("%03d", @user.code)}】#{@user.name}の情報を更新しました。"
      if admin_signed_in?
        redirect_to users_url
      else
        redirect_to @user
      end
    elsif @user.name.blank?
      flash[:alert] = "更新に失敗しました。<br>" + @user.errors.full_messages.join("<br>")
      redirect_to users_url
    else
      flash[:alert] = "#{@user.name}の更新に失敗しました。<br>" + @user.errors.full_messages.join("<br>")
      redirect_to users_url
    end
  end
  
  def password_update
    if @user.update_attributes(user_password_params)
      flash[:notice] = "【#{format("%03d", @user.code)}】#{@user.name}のパスワードを更新しました。"
      redirect_to users_url
    else
      flash[:alert] = "#{@user.name}の更新に失敗しました。<br>" + @user.errors.full_messages.join("<br>")
      redirect_to users_url
    end
  end
  
  def destroy
    @user.destroy
    flash[:alert] = "【#{format("%03d", @user.code)}】#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end
  
  private
  
    def user_params
      params.require(:user).permit(:code, :name, :email, :password, :password_confirmation)
    end
    
    def user_password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
    
    # 検索用
    def consignment_search_params
      params.fetch(:search, {}).permit(:customer_code, :customer_name, :product_code, :product_name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  
  def reminder_month
    Post.find(1).reminder_month
  end
  
  def reminder_consignments
    @user_consignments.each do
      @reminder = @user_consignments.where("ship_date < ?", Date.current - reminder_month.month).order(ship_date: :desc)
    end
    @reminder
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, method: :patch) do |f| %>
  <%= f.number_field :code, placeholder: "#{User.human_attribute_name :code}", class: "form-control" %>
  <%= f.text_field :name, placeholder: "#{User.human_attribute_name :name}", class: "form-control" %>
  <%= f.email_field :email, placeholder: "#{User.human_attribute_name :email}", class: "form-control" %>
  <%= f.submit "更新", data: { confirm: "#{user.name}の情報を更新してよろしいですか？" }, class: "btn btn-primary btn-block" %>
<% end %>

app/views/users/_password_form.html.erb
<%= form_with(model: user,url: password_update_user_path(user), local: true, method: :patch) do |f| %>
  <%= f.password_field :password, placeholder: "#{User.human_attribute_name :password}", class: "form-control" %>
  <%= f.password_field :password_confirmation, placeholder: "#{User.human_attribute_name :password_confirmation}", class: "form-control" %>
  <%= f.submit "パスワード変更", data: { confirm: "#{user.name}のパスワードを変更してよろしいですか？" }, class: "btn btn-danger btn-block" %>
<% end %>

app/views/users/_reminder.html.erb
<!-- リマインダーモーダル -->
<div class="modal fade" id="reminder-modal" tabindex="-1" role="dialog" aria-labelledby="modal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable modal-dialog-fluid modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="reminderModalTitle"><%= @user.name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <div class="modal-body">
        <table class="table main table-responsive table-bordered table-condensed table-hover bg-light center" id="table-products">
          <!-- PC画面 -->
          <thead class="pc-display reminder">
            <tr>
              <th>編集</th>
              <th><%= Consignment.human_attribute_name :ship_date %></th>
              <th><%= Consignment.human_attribute_name :product_name %></th>
              <th><%= Consignment.human_attribute_name :customer_name %></th>
              <th>委託残</th>
            </tr>
          </thead>
          
          <!-- Mobile画面 -->
          <thead class="mobile-display sub reminder">
            <tr>
              <th class="nowrap"><%= Consignment.human_attribute_name :ship_date %></th>
              <th>得意先 / 商品名</th>
              <th>残</th>
            </tr>
          </thead>
          
          <% if @user_consignments.present? %>
            <% reminder_consignments.each do |c| %>
              <!-- PC画面 -->
              <tbody class="pc-display reminder">
                <tr>
                  <td><%= link_to "", user_consignment_path(@user, c), class: "far fa-edit" %></td>
                  <td><%= c.ship_date %></td>
                  <td><%= c.product_name %></td>
                  <td><%= c.customer_name %></td>
                  <td><%= link_to total_consignment_balance(c), user_consignment_stocks_path(@user, c), class: "#{total_consignment_balance_color(c)}" %></td>
                </tr>
              </tbody>
              
              <!-- Mobile画面 -->
              <tbody class="mobile-display sub">
                <tr>
                  <td rowspan="2" class="dotted-right">
                    <%= link_to l(c.ship_date, format: :short), user_consignment_path(@user, c) %>
                    <a class=<%= stamp(c.created_at, c.updated_at) %>></a>
                  </td>
                  <td class="dashed-bottom none-border dotted-bottom"><%= c.customer_name %></td>
                  <td rowspan="2" class="dotted-left"><%= link_to "#{total_consignment_balance(c)}", user_consignment_stocks_path(@user, c), class: "#{total_consignment_balance_color(c)}" %></td>
                </tr>
                <tr>
                  <td class="none-border"><%= c.product_name %></td>
                </tr>
              </tbody>
            <% end %>
          <% end %>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
      </div>
    </div>
  </div>
</div>

app/views/users/end_tasks.html.erb
<% provide(:title, @user.name) %>

<h4>処理済</h4>
<div class="container">
  <div class="col col-md-12 user-menu">
    <div class="search-link-form">
      <div class="search-link">
        <%= link_to "戻る", @user, class: "btn btn-secondary" %>
      </div>
      <div class="search-link">
        <%= form_with(scope: :search, url: end_tasks_user_path(@user), class: "form-inline", method: :get, local: true) do |f| %>
          <div class="input-group mb-3">
            <%= f.text_field :customer_name, placeholder: "#{Customer.human_attribute_name :name}", class: "form-control" %>
            <%= f.text_field :product_name, placeholder: "#{Product.human_attribute_name :name}", class: "form-control" %>
            <div class="input-group-append">
              <%= f.submit "検索", class: "btn btn-sm btn-primary" %>
            </div>
          </div>
          <div class="ml-3 mb-3">
            <%= consignment_search_results_text(@user_consignments) %>&emsp;<%= consignment_search_results_link(end_tasks_user_path(@user)) %>
          </div>
        <% end %>
      </div>
    </div>

    <%= paginate @user_consignments if @search_none %>
    <table class="table main table-responsive table-bordered table-condensed table-hover bg-light" id="table-products">
      <!-- PC画面 -->
      <thead class="pc-display">
        <tr>
          <th width="6%">編集</th>
          <th width="11%" class="nowrap"><%= Consignment.human_attribute_name :ship_date %></th>
          <th width="28%"><%= Product.human_attribute_name :name %></th>
          <th width="8%">委託残</th>
          <th width="12%"><%= Consignment.human_attribute_name :serial_number %></th>
          <th width="20%"><%= Consignment.human_attribute_name :customer_name %></th>
          <th width="15%"><%= Consignment.human_attribute_name :note %></th>
        </tr>
      </thead>
      
      <!-- Mobile画面 -->
      <thead class="mobile-display sub">
        <tr>
          <th class="nowrap">委託日</th>
          <th>得意先 / 商品名</th>
          <th>残</th>
        </tr>
      </thead>
      
      <% @user_consignments.decorate.each do |c| %>
        <!-- PC画面 -->
        <tbody class="pc-display">
          <tr>
            <td><%= link_to "", user_consignment_path(@user, c), class: "far fa-edit" %></td>
            <td><%= l(c.ship_date, format: :default) %><a class=<%= stamp(c.created_at, c.updated_at) %>></a></td>
            <td><%= c.product_id_num&.name %></td>
            <td><%= link_to total_consignment_balance(c), user_consignment_stocks_path(@user, c), class: "#{total_consignment_balance_color(c)}" %></td>
            <td><%= c.serial_number %></td>
            <td><%= c.customer_id_num&.name %></td>
            <td><%= c.note %></td>
          </tr>
        </tbody>
        
        <!-- Mobile画面 -->
        <tbody class="mobile-display sub">
          <tr>
            <td rowspan="2" class="dotted-right"><%= link_to l(c.ship_date, format: :short), user_consignment_path(@user, c) %></td>
            <td class="dashed-bottom none-border dotted-bottom"><%= c.customer_id_num&.name %></td>
            <td rowspan="2" class="dotted-left"><%= link_to "#{total_consignment_balance(c)}", user_consignment_stocks_path(@user, c), class: "#{total_consignment_balance_color(c)}" %></td>
          </tr>
          <tr>
            <td class="none-border"><%= c.product_id_num&.name %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "担当者一覧") %>

<h2>担当者一覧・編集</h2>
<div class="container">
  <div class="col col-md-12 admin-menu">
    <%= paginate @users %>
    <table class="table-responsive table-bordered table-condensed table-hover bg-light" id="table-users">
      <thead>
        <tr height="50">
          <% if admin_signed_in? %>
            <th class="pc-width">
              <!-- 登録 -->
              <%= link_to "", new_user_registration_path, class: "fas fa-plus-circle fa-lg" %>
            </th>
          <% end %>
          <th class="pc-display"><%= User.human_attribute_name :code %></th>
          <th><%= User.human_attribute_name :name %></th>
          <th class="pc-display">
            <%= User.human_attribute_name :email %>
          </th>
          <% if admin_signed_in? %>
            <th></th>
          <% end %>
        </tr>
      </thead>
      
      <% @users.each do |user| %>
        <tr height="40">
          <% if admin_signed_in? %>
            <td>
              <a class="btn btn-primary fas fa-edit" data-toggle="collapse" href="#collapse1-<%= user.id %>"
                 role="button" aria-expanded="false" aria-controls="collapse1-<%= user.id %>">
                <!-- 編集 -->
              </a>
              <a class="btn btn-danger fas fa-unlock-alt" data-toggle="collapse" href="#collapse2-<%= user.id %>"
                 role="button" aria-expanded="false" aria-controls="collapse2-<%= user.id %>">
              </a>
            </td>
          <% end %>
          <td class="pc-display"><%= format("%03d", user.code) %><a class=<%= stamp(user.created_at, user.updated_at) %>></td>
          <td><%= user.name %></td>
          <td class="pc-display"><%= user.email %></td>
          <% if admin_signed_in? %>
            <td>
              <!-- 削除 -->
              <%= link_to "", user_path(user), method: :delete,
                                               data: { confirm: "【#{format("%03d", user.code)}】#{user.name}のデータを削除しますか？" },
                                               class: "fas fa-times-circle fa-lg" %>
            </td>
          <% end %>
        </tr>
        <tr>
          <td colspan="5">
            <div class="collapse" id="collapse1-<%= user.id %>">
              <div class="collapse-body">
                <%= render 'form', { user: user } %>
              </div>
            </div>
            <div class="collapse" id="collapse2-<%= user.id %>">
              <div class="collapse-body">
                <%= render 'password_form', { user: user } %>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<h4><%= @user.name %></h4>
<% if @user_consignments.present? %>
  <% if reminder_consignments.present? %>
    <p class="center reminder-area">
      <%= button_tag type: "button", data: {toggle: "modal", target: "#reminder-modal"}, class: "btn btn-outline-danger reminder-message" do %>
        <%= "#{reminder_month}ヶ月経過した委託が#{@reminder.count}件あります。" %>
      <% end %>
    </p>
  <% end %>
<% end %>

<div class="container">
  <div class="col col-md-12 user-menu">
    <!--<div class="search-link-form mobile-display">-->
    <!--  <div class="search-link"><= link_to "委託登録", new_user_consignment_path(@user), class: "btn btn-primary" %></div>-->
    <!--</div>-->
    <div class="search-link-form">
      <div class="search-link"><%= link_to "委託登録", new_user_consignment_path(@user), class: "btn btn-primary" %></div>
      <div class="search-link"><%= link_to "得意先別", by_customer_user_consignments_path(@user), class: "btn btn-outline-primary" %></div>
      <div class="search-link"><%= link_to "商品別",  by_product_user_consignments_path(@user), class: "btn btn-outline-primary" %></div>
      <div class="search-link"><%= link_to "担当別",  by_user_user_consignments_path(@user), class: "btn btn-outline-primary" %></div>
      <div class="search-link"><%= link_to "処理済",  end_tasks_user_path(@user), class: "btn btn-outline-secondary" %></div>
      <div class="search-link">
        <%= form_with(scope: :search, url: user_path(@user), class: "form-inline", method: :get, local: true) do |f| %>
          <div class="input-group mb-3">
            <%= f.text_field :customer_name, placeholder: "#{Customer.human_attribute_name :name}", class: "form-control" %>
            <%= f.text_field :product_name, placeholder: "#{Product.human_attribute_name :name}", class: "form-control" %>
            <div class="input-group-append">
              <%= f.submit "検索", class: "btn btn-sm btn-primary" %>
            </div>
          </div>
          <div class="ml-3 mb-3">
            <%= consignment_search_results_text(@user_consignments) %>&emsp;<%= consignment_search_results_link(user_path(@user)) %>
          </div>
        <% end %>
      </div>
    </div>

    <%= paginate @user_consignments if @search_none %>
    
    <table class="table main table-responsive table-bordered table-condensed table-hover bg-light" id="table-products">
      <!-- PC画面 -->
      <thead class="pc-display">
        <tr>
          <th width="6%">編集</th>
          <th width="11%" class="nowrap"><%= Consignment.human_attribute_name :ship_date %></th>
          <th width="28%"><%= Product.human_attribute_name :name %></th>
          <th width="8%">委託残</th>
          <th width="12%"><%= Consignment.human_attribute_name :serial_number %></th>
          <th width="20%"><%= Consignment.human_attribute_name :customer_name %></th>
          <th width="15%"><%= Consignment.human_attribute_name :note %></th>
        </tr>
      </thead>
      
      <!-- Mobile画面 -->
      <thead class="mobile-display sub">
        <tr>
          <th class="nowrap"><%= Consignment.human_attribute_name :ship_date %></th>
          <th>得意先 / 商品名</th>
          <th>残</th>
        </tr>
      </thead>
      
      <% @user_consignments.decorate.each do |c| %>
        <!-- PC画面 -->
        <tbody class="pc-display">
          <tr>
            <td><%= link_to "", user_consignment_path(@user, c), class: "far fa-edit" %></td>
            <td><%= l(c.ship_date, format: :default) %><a class=<%= stamp(c.created_at, c.updated_at) %>></a></td>
            <td><%= c.product_id_num&.name %></td>
            <td><%= link_to total_consignment_balance(c), user_consignment_stocks_path(@user, c), class: "#{total_consignment_balance_color(c)}" %></td>
            <td><%= c.serial_number %></td>
            <td><%= c.customer_id_num&.name %></td>
            <td><%= c.note %></td>
          </tr>
        </tbody>
        
        <!-- Mobile画面 -->
        <tbody class="mobile-display sub">
          <tr>
            <td rowspan="2" class="dotted-right">
              <%= link_to l(c.ship_date, format: :short), user_consignment_path(@user, c) %>
              <a class=<%= stamp(c.created_at, c.updated_at) %>></a>
            </td>
            <td class="dashed-bottom none-border dotted-bottom"><%= c.customer_id_num&.name %></td>
            <td rowspan="2" class="dotted-left"><%= link_to "#{total_consignment_balance(c)}", user_consignment_stocks_path(@user, c), class: "#{total_consignment_balance_color(c)}" %></td>
          </tr>
          <tr>
            <td class="none-border"><%= c.product_id_num&.name %></td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
</div>

<!-- リマインダーモーダル -->
<%= render 'reminder' %>