config/routes.rb
Rails.application.routes.draw do
  # get 'consignments/new'
  root 'top_pages#top'
  
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations' # ユーザー情報更新
  }
  
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy' # logout
  end
  
  resources :admins, only: %i(show index)
  
  resources :users, only: %i(index show update destroy) do
    resources :consignments do
      collection do
        get 'by_customer', to: 'consignments#by_customer'
        get 'by_user', to: 'consignments#by_user'
        get 'by_product', to: 'consignments#by_product'
        get 'documents'
      end
      resources :stocks
    end
    member do
      patch 'password_update' # パスワード更新
      get 'end_tasks'
    end
  end
  
  resources :products do
    collection do
      post 'import'
    end
  end
  
  resources :customers do
    collection do
      post 'import'
    end
  end
  
  resources :posts, only: %i(show edit update)
  
  post 'callback', to: 'linebot#callback'

end

app/models/consignment.rb
class Consignment < ApplicationRecord
  belongs_to :user
  has_many :stocks, dependent: :destroy
  accepts_nested_attributes_for :stocks
  
  validates :ship_date, presence: true
  validates :customer_id_number, presence: true
  validates :customer_code, presence: true, length: {maximum: 13 }
  validates :customer_name, presence: true, length: {maximum: 40 }
  validates :product_id_number, presence: true
  validates :product_code, presence: true, length: {maximum: 13 }
  validates :product_name, presence: true, length: {maximum: 40 }
  validates :quantity, presence: true, numericality: { greater_than: 0 }
  validates :serial_number, length: { maximum: 50 }
  validates :note, length: { maximum: 100 }
  validates :user_name, presence: true
  after_validation :remove_consignment_error_messages
  
  # 委託情報登録時、不要なバリデーションの表示をさせない。
  def remove_consignment_error_messages
    errors.messages.delete(:customer_id_number)
    errors.messages.delete(:product_id_number)
    errors.messages.delete(:user_name)
  end
  
  # 検索
  scope :search, -> (search_params) do
    return if search_params.blank?
    customer_name_like(search_params[:customer_name]).product_name_like(search_params[:product_name]).user_name_like(search_params[:user_name])
  end
  scope :customer_name_like, -> (customer_name) { where('customer_name LIKE ?', "%#{customer_name}%") if customer_name.present? }
  scope :product_name_like, -> (product_name) { where('product_name LIKE ?', "%#{product_name}%") if product_name.present? }
  scope :user_name_like, -> (user_name) { where('user_name LIKE ?', "%#{user_name}%") if user_name.present? }
end

app/controllers/consignments_controller.rb
class ConsignmentsController < ApplicationController
  before_action :signed_in_user
  before_action :set_user_consignments
  before_action :authenticate_user!, only: %i(by_customer by_product)
  before_action :set_consignment, only: %i(show edit update destroy)
  before_action :signed_in_correct_user, only: %i(index show by_customer by_product new create edit update destroy)
  
  def index
    redirect_to new_user_consignment_path
  end
  
  def show
  end
  
  def by_customer
    @search_params = consignment_search_params
    @search_none = consignment_search_none
    @consignments = @search_none ? Consignment.where(done: false).order(customer_code: :asc).group_by(&:customer_id_number) : 
                                   Consignment.where(done: false).search(@search_params).order(customer_code: :asc).group_by(&:customer_id_number)
    @customers_pdf = Consignment.where(done: false).order(customer_code: :asc).group_by(&:customer_id_number)
  end
  
  def by_product
    @search_params = consignment_search_params
    @search_none = consignment_search_none
    @consignments = @search_none ? Consignment.where(done: false).order(product_code: :asc).group_by(&:product_id_number) : 
                                   Consignment.where(done: false).search(@search_params).order(product_code: :asc).group_by(&:product_id_number)
    @products_pdf = Consignment.where(done: false).order(product_code: :asc).group_by(&:product_id_number)
  end
  
  def by_user
    @search_params = consignment_search_params
    @search_none = consignment_search_none
    @consignments = @search_none ? Consignment.where(done: false).order(user_id: :asc).group_by(&:user_id) : 
                                   Consignment.where(done: false).search(@search_params).order(user_id: :asc).group_by(&:user_id)
    @users_pdf = Consignment.where(done: false).order(user_id: :asc).group_by(&:user_id)
  end
  
  def documents
    @documents = params[:text]
    @customers_pdf = Consignment.where(done: false).order(customer_code: :asc).group_by(&:customer_id_number)
    @products_pdf = Consignment.where(done: false).order(product_code: :asc).group_by(&:product_id_number)
    @users_pdf = Consignment.where(done: false).order(user_id: :asc).group_by(&:user_id)
    # @customers = @user.consignments.where(done: false).order(customer_code: :asc).group_by(&:customer_id_number) # pdf上で使用するレコードのインスタンスを作成
    respond_to do |format|
      format.html
      format.pdf do

        # pdfを新規作成。インスタンスを渡す。
        pdf = ConsignmentPdf.new(@customers_pdf, @products_pdf, @users_pdf, @documents)

        send_data pdf.render,
          filename:    "委託一覧表(#{Date.current}).pdf",
          type:        "application/pdf",
          disposition: "inline" # 画面に表示。外すとダウンロードされる。
      end
    end
  end
  
  def new
    @customers = Customer.all.order(code: :asc)
    @products = Product.all.order(code: :asc)
    @consignment = Consignment.new
    @consignment.stocks.build
  end
  
  def create
    @customers = Customer.all
    @products = Product.all
    @consignment = @user.consignments.build(consignment_params)
    if @consignment.save
      flash[:notice] = "登録完了。"
      redirect_to @user
    else
      flash.now[:alert] = "登録に失敗しました、赤枠内は必須です。<br>" + error_message
      render :new
    end
  rescue ActiveRecord::NotNullViolation
    flash[:alert] = "委託数量が入力されていません。"
    render :new
  end
  
  def edit
    @customers = Customer.all
    @products = Product.all
  end
  
  def update
    ActiveRecord::Base.transaction do
      @consignment.update_attributes!(consignment_params)
      done_decision
      flash[:notice] = "委託情報を更新しました。"
      redirect_to @user
    end
  rescue ActiveRecord::RecordInvalid
    flash.now[:alert] = "更新に失敗しました。<br>" + error_message
    render :edit
  end
  
  def destroy
    @consignment.destroy
    flash[:alert] = "【#{@consignment.customer_code}】#{@consignment.product_code}&emsp;削除完了。"
    redirect_to @user
  end
  
  private
  
    def consignment_params
      params.require(:consignment).permit(:ship_date, :customer_id_number, :customer_code, :customer_name,
                                          :product_id_number, :product_code, :product_name, :serial_number,
                                          :quantity, :note, :user_name, :user_id)
    end
    
    def set_user_consignments
      @user = User.find(params[:user_id])
    end
    
    def set_consignment
      unless @consignment = @user.consignments.find_by(id: params[:id]).decorate
        flash[:alert] = "アクセス権限がありません。"
        redirect_to @user
      end
    end
    
    # 検索用
    def consignment_search_params
      params.fetch(:search, {}).permit(:customer_code, :customer_name, :product_code, :product_name, :user_name)
    end
end

app/helpers/consignments_helper.rb
module ConsignmentsHelper
  # エラーメッセージ
  def error_message
    @consignment.errors.full_messages.join("<br>")
  end
  
  # user, consignment側で使用。委託残数合計 create updateにも@stocks = @user.consignments.find(params[:consignment_id]).stocksを設定しないとvalidation時、undefined method mapのエラーが発生する。
  def consignment_remaining_count
    @user.consignments.find(params[:consignment_id]).quantity - @stocks.map { |s| s.return_quantity }.sum - @stocks.map { |s| s.sales_quantity }.sum
  end
  
  # user, consignment側で使用。委託残数合計がマイナスの場合、文字色赤色にする。
  def consignment_remaining_count_color
    if consignment_remaining_count < 0
      "minus"
    end
  end
  
  # stock側で使用。委託残数合計 consignment.quantityがnilの場合、計算を飛ばして表示させエラーを回避
  def total_consignment_balance(c)
    # if c.quantity != nil
      # @stocks = @user.consignments.find_by(params[:consignment_id]).stocks
      # @stocks = @user.consignments.find_by(params[:consignment_id])
      c.quantity - c.stocks.map { |s| s.return_quantity }.sum - c.stocks.map { |s| s.sales_quantity }.sum
    # end
  end
  
  # stock側で使用。委託残数合計がマイナスの場合、文字色赤色にする。
  def total_consignment_balance_color(c)
    if total_consignment_balance(c) < 0
      "minus"
    end
  end
  
  # 0以外の委託残数
  def none_zero_total(c)
    total_consignment_balance(c) != 0
  end
  
  # 検索フォームが未入力の時
  def consignment_search_none
    @search_params.blank? || @search_params[:customer_name] == "" && @search_params[:product_name] == "" && @search_params[:user_name] == ""
  end
  
  # 検索結果の表示
  def consignment_search_results_text(search_hash)
    if @search_params[:customer_name] == "" && @search_params[:product_name] == ""
      "検索ワードを入力してください。"
    elsif params[:search].present?
      "検索結果 #{search_hash.count}件"
    end
  end
  
  def consignment_search_results_link(path)
    if @search_params[:customer_name] == "" && @search_params[:product_name] == ""
      return
    elsif params[:search].present?
      link_to "戻る", path
    end
  end
  
  # 得意先別の検索
  def by_customer_search_none
    @search_params.blank? || @search_params[:customer_name] == ""
  end
  
  def by_customer_search_results_text(search_hash)
    if @search_params[:customer_name] == ""
      "検索ワードを入力してください。"
    elsif params[:search].present?
      "検索結果 #{search_hash.count}件"
    end
  end
  
  def by_customer_search_results_link(path)
    if @search_params[:customer_name] == ""
      return
    elsif params[:search].present?
      link_to "戻る", path
    end
  end
  
  # 商品別の検索
  def by_product_search_none
    @search_params.blank? || @search_params[:product_name] == ""
  end
  
  def by_product_search_results_text(search_hash)
    if @search_params[:product_name] == ""
      "検索ワードを入力してください。"
    elsif params[:search].present?
      "検索結果 #{search_hash.count}件"
    end
  end
  
  def by_product_search_results_link(path)
    if @search_params[:product_name] == ""
      return
    elsif params[:search].present?
      link_to "戻る", path
    end
  end
  
  # 担当者別の検索
  def by_user_search_none
    @search_params.blank? || @search_params[:user_name] == ""
  end
  
  def by_user_search_results_text(search_hash)
    if @search_params[:user_name] == ""
      "検索ワードを入力してください。"
    elsif params[:search].present?
      "検索結果 #{search_hash.count}件"
    end
  end
  
  def by_user_search_results_link(path)
    if @search_params[:user_name] == ""
      return
    elsif params[:search].present?
      link_to "戻る", path
    end
  end
end

app/views/consignments/_form.html.erb
<div class="consignment-form">
  <%= f.date_field :ship_date, value: yield(:text), placeholder: "#{Consignment.human_attribute_name :ship_date}",
                               class: "form-control" %>
</div>

<div class="consignment-form-btn">
  <%= button_tag type: "button", data: {toggle: "modal", target: "#customer-modal"},
                                 class: "btn btn-sm btn-primary" do %>
    得意先検索
  <% end %>
</div>

<div class="consignment-form">
  <%= f.hidden_field :customer_id_number, id: "output_customer_id", class: "form-control", readonly: true %>
  <%= f.text_field :customer_code, placeholder: "#{Consignment.human_attribute_name :customer_code}",
                                   id: "output_customer_code", class: "form-control", readonly: true %>
  <%= f.text_field :customer_name, placeholder: "#{Consignment.human_attribute_name :customer_name}",
                                   id: "output_customer_name", class: "form-control", readonly: true %>
</div>

<div class="consignment-form-btn">
  <%= button_tag type: "button", data: {toggle: "modal", target: "#product-modal"},
                                 class: "btn btn-sm btn-primary" do %>
    &nbsp;&nbsp;商品検索&nbsp;&nbsp;
  <% end %>
</div>

<div class="consignment-form">
  <%= f.hidden_field :product_id_number, id: "output_product_id", class: "form-control", readonly: true %>
  <%= f.text_field :product_code, placeholder: "#{Consignment.human_attribute_name :product_code}",
                                  id: "output_product_code", class: "form-control", readonly: true %>
  <%= f.text_field :product_name, placeholder: "#{Consignment.human_attribute_name :product_name}",
                                   id: "output_product_name", class: "form-control", readonly: true %>
</div>

<div class="consignment-form">
  <%= f.number_field :quantity, step: 1, placeholder: "#{Consignment.human_attribute_name :quantity}", class: "form-control" %>
</div>

<div class="consignment-form">
  <%= f.text_field :serial_number, placeholder: "#{Consignment.human_attribute_name :serial_number}", class: "form-control" %>
</div>

<div class="consignment-form">
  <%= f.text_area :note, placeholder: "#{Consignment.human_attribute_name :note}", class: "form-control" %>
  <%= f.hidden_field :user_name, value: @user.name, class: "form-control", readonly: true %>
</div>

<div class="consignment-form btn-field">
  <div class="btn-item">
    <%= f.submit yield(:button_text), class: "btn btn-primary btn-block" %>
  </div>
  <div class="btn-item">
    <%= link_to "戻る", user_path(@user), class: "btn btn-secondary btn-block" %>
  </div>
</div>

app/views/consignments/by_customer.html.erb
<% provide(:title, "得意先別委託情報") %>

<h4>得意先別委託</h4>
<div class="container">
  <div class="col col-md-12 user-menu">
    <div class="search-link-form">
      <% unless admin_signed_in? %>
        <div class="search-link">
          <%= link_to "#{@user.name}", @user, class: "btn btn-outline-primary" %>
        </div>
      <% end %>
      <div class="search-link">
        <%= link_to "商品別", by_product_user_consignments_path(@user), class: "btn btn-outline-primary" %>
      </div>
      <div class="search-link">
        <p class="pc-display">
          <%= link_to "PDF", documents_user_consignments_path(text: "customers_pdf", format: "pdf"), :target=>["_blank"], class: "btn btn-danger" %>
        </p>
      </div>
      <div class="search-link">
        <%= form_with(scope: :search, url: by_customer_user_consignments_path(@user), class: "form-inline", method: :get, local: true) do |f| %>
          <div class="input-group mb-3">
            <%= f.text_field :customer_name, placeholder: "#{Customer.human_attribute_name :name}", class: "form-control" %>
            <div class="input-group-append">
              <%= f.submit "検索", class: "btn btn-sm btn-primary" %>
            </div>
          </div>
          <div class="ml-3 mb-3">
            <%= by_customer_search_results_text(@consignments) %>&emsp;<%= by_customer_search_results_link(by_customer_user_consignments_path(@user)) %>
          </div>
        <% end %>
      </div>
    </div>
    
    <% @consignments.each do |customer_id_number, consignments| %>
      <table class="table every table-responsive table-bordered table-condensed bg-light">
        <thead>
          <!-- PC画面 -->
          <tr class="pc-display">
            <th colspan="4" class="every">【<%= Customer.find(customer_id_number).code %>】<%= Customer.find(customer_id_number).name %></th>
          </tr>
          <!-- Mobile画面 -->
          <tr class="mobile-display">
            <th class="every"><%= Customer.find(customer_id_number).name %></th>
            <th class="every">残</th>
          </tr>
        </thead>
        
        <tbody>
          <!-- PC画面 -->
          <tr class="pc-display">
            <th width="15%"><%= Product.human_attribute_name :code %></th>
            <th width="45%"><%= Product.human_attribute_name :name %></th>
            <th width="10%">委託残</th>
            <th width="30%">担当者</th>
          </tr>
          <% consignments.each do |consignment| %>
            <!-- PC画面 -->
            <tr class="pc-display">
              <td><%= Product.find(consignment.product_id_number).code %></td>
              <td><%= Product.find(consignment.product_id_number).name %></td>
              <td class="<%= total_consignment_balance_color(consignment) %>">
                <%= stock_link(consignment) %>
              </td>
              <td><%= User.find(consignment.user_id).name %></td>
            </tr>
            
            <!-- Mobile画面 -->
            <tr class="mobile-display">
              <td width="90%" class="font-small">
                <%= Product.find(consignment.product_id_number).name %><br>
                <a class="font-xxsmall">
                  <%= "担当:#{User.find(consignment.user_id).name}" %>
                </a>
              </td>
              <td width="10%" class="<%= total_consignment_balance_color(consignment) %>">
                <%= stock_link(consignment) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
    <% end %>
  </div>
</div>

app/views/consignments/by_product.html.erb
<% provide(:title, "商品別委託情報") %>

<h4>商品別委託</h4>
<div class="container">
  <div class="col col-md-12 user-menu">
    <div class="search-link-form">
      <div class="search-link">
        <%= link_to "#{@user.name}", @user, class: "btn btn-outline-primary" %>
      </div>
      <div class="search-link">
        <%= link_to "得意先別", by_customer_user_consignments_path(@user), class: "btn btn-outline-primary" %>
      </div>
      <div class="search-link">
        <%= link_to "担当別",  by_user_user_consignments_path(@user), class: "btn btn-outline-primary" %>
      </div>
      <div class="search-link">
        <p class="pc-display">
          <%= link_to "PDF", documents_user_consignments_path(text: "products_pdf", format: "pdf"), :target=>["_blank"], class: "btn btn-danger" %>
        </p>
      </div>
      <div class="search-link">
        <%= form_with(scope: :search, url: by_product_user_consignments_path(@user), class: "form-inline", method: :get, local: true) do |f| %>
          <div class="input-group mb-3">
            <%= f.text_field :product_name, placeholder: "#{Product.human_attribute_name :name}", class: "form-control" %>
            <div class="input-group-append">
              <%= f.submit "検索", class: "btn btn-sm btn-primary" %>
            </div>
          </div>
          <div class="ml-3 mb-3">
            <%= by_product_search_results_text(@consignments) %>&emsp;<%= by_product_search_results_link(by_product_user_consignments_path(@user)) %>
          </div>
        <% end %>
      </div>
    </div>
    
    <% @consignments.each do |product_id_number, consignments| %>
      <table class="table every default table-responsive table-bordered table-condensed bg-light">
        <thead>
          <!-- PC画面 -->
          <tr class="pc-display">
            <th colspan="5" class="every">【<%= Product.find(product_id_number).code %>】<%= Product.find(product_id_number).name %></th>
          </tr>
          <!-- Mobile画面 -->
          <tr class="mobile-display">
            <th class="every"><%= Product.find(product_id_number).name %></th>
            <th class="every">残</th>
          </tr>
        </thead>
        
        <tbody>
          <!-- PC画面 -->
          <tr class="pc-display">
            <th width="10%"><%= Consignment.human_attribute_name :ship_date %></th>
            <th width="15%"><%= Customer.human_attribute_name :code %></th>
            <th width="45%"><%= Customer.human_attribute_name :name %></th>
            <th width="10%">委託残</th>
            <th width="20%">担当者</th>
          </tr>
          <% consignments.each do |consignment| %>
            <!-- PC画面 -->
            <tr class="pc-display">
              <td>
                <%= l(consignment.ship_date, format: :short) %>
                <a class=<%= stamp(consignment.created_at, consignment.updated_at) %>></a>
              </td>
              <td><%= Customer.find(consignment.customer_id_number).code %></td>
              <td><%= Customer.find(consignment.customer_id_number).name %></td>
              <td class="<%= total_consignment_balance_color(consignment) %>">
                <%= stock_link(consignment) %>
              </td>
              <td><%= User.find(consignment.user_id).name %></td>
            </tr>
            
            <!-- Mobile画面 -->
            <tr class="mobile-display">
              <td width="90%" class="font-small">
                <%= Customer.find(consignment.customer_id_number).name %><br>
                <a class="font-xxsmall">
                  <%= l(consignment.ship_date, format: :short) %><a class=<%= stamp(consignment.created_at, consignment.updated_at) %>></a>
                  <%= "担当:#{User.find(consignment.user_id).name}" %>
                </a>
              </td>
              <td width="10%" class="<%= total_consignment_balance_color(consignment) %>">
                <%= stock_link(consignment) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
    <% end %>
  </div>
</div>

app/views/consignments/by_user.html.erb
<% provide(:title, "担当者別委託情報") %>

<h4>担当者別委託</h4>
<div class="container">
  <div class="col col-md-12 user-menu">
    <div class="search-link-form">
      <div class="search-link">
        <%= link_to "#{@user.name}", @user, class: "btn btn-outline-primary" %>
      </div>
      <div class="search-link">
        <%= link_to "得意先別", by_customer_user_consignments_path(@user), class: "btn btn-outline-primary" %>
      </div>
      <div class="search-link">
        <%= link_to "商品別", by_product_user_consignments_path(@user), class: "btn btn-outline-primary" %>
      </div>
      <div class="search-link">
        <p class="pc-display">
          <%= link_to "PDF", documents_user_consignments_path(text: "users_pdf", format: "pdf"), :target=>["_blank"], class: "btn btn-danger" %>
        </p>
      </div>
      <div class="search-link">
        <%= form_with(scope: :search, url: by_user_user_consignments_path(@user), class: "form-inline", method: :get, local: true) do |f| %>
          <div class="input-group mb-3">
            <%= f.text_field :user_name, placeholder: "#{User.human_attribute_name :name}", class: "form-control" %>
            <div class="input-group-append">
              <%= f.submit "検索", class: "btn btn-sm btn-primary" %>
            </div>
          </div>
          <div class="ml-3 mb-3">
            <%= by_user_search_results_text(@consignments) %>&emsp;<%= by_user_search_results_link(by_user_user_consignments_path(@user)) %>
          </div>
        <% end %>
      </div>
    </div>
    
    <% @consignments.each do |user_id, consignments| %>
      <table class="table every default table-responsive table-bordered table-condensed bg-light">
        <thead>
          <!-- PC画面 -->
          <tr class="pc-display">
            <th colspan="5" class="every"><%= User.find(user_id).name %></th>
          </tr>
          <!-- Mobile画面 -->
          <tr class="mobile-display">
            <th class="every"><%= User.find(user_id).name %></th>
            <th class="every">残</th>
          </tr>
        </thead>
        
        <tbody>
          <!-- PC画面 -->
          <tr class="pc-display">
            <th width="10%"><%= Consignment.human_attribute_name :ship_date %></th>
            <th width="20%"><%= Product.human_attribute_name :code %></th>
            <th width="30%"><%= Product.human_attribute_name :name %></th>
            <th width="30%"><%= Customer.human_attribute_name :name %></th>
            <th width="10%">委託残</th>
          </tr>
          <% consignments.each do |consignment| %>
            <!-- PC画面 -->
            <tr class="pc-display">
              <td>
                <%= l(consignment.ship_date, format: :short) %>
                <a class=<%= stamp(consignment.created_at, consignment.updated_at) %>></a>
              </td>
              <td><%= Product.find(consignment.product_id_number).code %></td>
              <td><%= Product.find(consignment.product_id_number).name %></td>
              <td><%= Customer.find(consignment.customer_id_number).name %></td>
              <td class="<%= total_consignment_balance_color(consignment) %>">
                <%= stock_link(consignment) %>
              </td>
            </tr>
            
            <!-- Mobile画面 -->
            <tr class="mobile-display">
              <td width="90%" class="font-small">
                <%= Product.find(consignment.product_id_number).name %><br>
                <a class="font-xxsmall">
                  <%= l(consignment.ship_date, format: :short) %><a class=<%= stamp(consignment.created_at, consignment.updated_at) %>></a>
                  <%= "委託先:#{Customer.find(consignment.customer_id_number).name}" %>
                </a>
              </td>
              <td width="10%" class="<%= total_consignment_balance_color(consignment) %>">
                <%= stock_link(consignment) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <br>
    <% end %>
  </div>
</div>

app/views/consignments/edit.html.erb
<% provide(:title, "委託商品編集") %>
<% provide(:button_text, "更新") %>
<% provide(:text, @consignment.ship_date) %>

<h1>委託商品編集</h1>
<div class="row justify-content-md-center">
  <div class="col col-md-6 col-md-offset-3">
    <%= form_with(model: @consignment, url: user_consignment_path(@user, @consignment), local: true, method: :patch) do |f| %>
      <%= render 'form', f: f %>
    <% end %>
  </div>
</div>

<!-- 得意先検索モーダル -->
<%= render 'customer_search' %>

<!-- 商品検索モーダル -->
<%= render 'product_search' %>

app/views/consignments/new.html.erb
<% provide(:title, "委託商品登録") %>
<% provide(:button_text, "登録") %>
<% provide(:text, Date.current) %>

<h3>委託商品登録</h3>
<div class="row justify-content-md-center">
  <div class="col col-md-6 col-md-offset-3">
    <%= form_with(model: @consignment, url: user_consignments_path(@user), local: true) do |f| %>
      <%= render 'form', f: f %>
    <% end %>
  </div>
</div>

<!-- 得意先検索モーダル -->
<%= render 'customer_search' %>

<!-- 商品検索モーダル -->
<%= render 'product_search' %>

app/views/consignments/show.html.erb
<% provide(:title, "委託情報詳細") %>

<h1>委託情報詳細</h1>
<div class="row justify-content-md-center consignment-show">
  <div class="col col-md-6 col-md-offset-3">
    <table class="table table-bordered table-condensed bg-light">
      <tbody>
        <tr>
          <th width="130"><%= Consignment.human_attribute_name :ship_date %></th>
          <td><%= l(@consignment.ship_date, format: :default)  %></td>
        </tr>
        <tr>
          <th><%= Consignment.human_attribute_name :customer_code %></th>
          <td><%= @consignment.customer_id_num.code %></td>
        </tr>
        <tr>
          <th><%= Consignment.human_attribute_name :customer_name %></th>
          <td><%= @consignment.customer_id_num.name %></td>
        </tr>
        <tr>
          <th><%= Consignment.human_attribute_name :product_code %></th>
          <td><%= @consignment.product_id_num.code %></td>
        </tr>
        <tr>
          <th><%= Consignment.human_attribute_name :product_name %></th>
          <td><%= @consignment.product_id_num.name %></td>
        </tr>
        <tr>
          <th><%= Consignment.human_attribute_name :quantity %></th>
          <td>
            <%= @consignment.quantity %>
            <!--< @consignment.stocks.each do |stock| %>-->
            <!--  <= stock_result(stock) %>-->
            <!--< end %>-->
          </td>
        </tr>
        <tr>
          <th><%= Consignment.human_attribute_name :serial_number %></th>
          <td><%= @consignment.serial_number %></td>
        </tr>
        <tr>
          <th><%= Consignment.human_attribute_name :note %></th>
          <td><%= @consignment.note %></td>
        </tr>
        <tr>
          <th><%= User.human_attribute_name :name %></th>
          <td><%= @user.name %></td>
        </tr>
      </tbody>
    </table>
    <div class="btn-field">
      <div class="btn-item-2">
        <%= link_to "編集", edit_user_consignment_path(@user, @consignment), class: "btn btn-primary btn-block" %>
      </div>
      <div class="btn-item-2">
        <%= link_to "戻る", user_path(@user), class: "btn btn-secondary btn-block" %>
      </div>
      <div class="btn-item-3">
        <%= link_to "削除", user_consignment_path, method: :delete,
                            data: { confirm: "#{@consignment.customer_code}【#{@consignment.product_code}】を削除しますか？" },
                            class: "btn btn-danger btn-block" %>
      </div>
    </div>
    </div>
  </div>
</div>